=== pypi-data/pypi-mirror-33/packages/xmlschema/xmlschema-0.9.31-py2.py3-none-any.whl/xmlschema/tests/cases/features/decoding/decoder.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://example.com/decoder" xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://example.com/decoder" >
    <xs:element name="data">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="decimal_value" type="Decimal_9_5" maxOccurs="unbounded"/>
                <xs:element name="celsiusBodyTemp" type="celsiusBodyTemp" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="certification" type="year_attr_string_75" maxOccurs="unbounded"/>
                <xs:element name="menÃ¹" type="xs:string"/>
                <xs:element name="complex_boolean" type="TYPE_ATTR_BOOLEAN" minOccurs="0" maxOccurs="4"/>
                <xs:element name="simple_boolean" type="xs:boolean" minOccurs="0" maxOccurs="4"/>
                <xs:element name="date_and_time" type="xs:dateTime" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="Decimal_9_5">
        <xs:restriction base="xs:decimal">
            <xs:totalDigits value="9"/>
            <xs:fractionDigits value="5"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name='celsiusBodyTemp'>
        <xs:restriction base='xs:decimal'>
            <xs:totalDigits value='4'/>
            <xs:fractionDigits value='1'/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="string_75">
        <xs:restriction base="xs:string">
            <xs:maxLength value="75"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="year_attr_string_75">
        <xs:simpleContent>
            <xs:extension base="string_75">
                <xs:attribute name="Year" type="xs:integer" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="TYPE_ATTR_BOOLEAN">
        <xs:simpleContent>
            <xs:extension base="xs:boolean">
                <xs:attribute name="Type" type="xs:integer" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== pypi-data/pypi-mirror-33/packages/xmlschema/xmlschema-0.9.31-py2.py3-none-any.whl/xmlschema/tests/cases/features/decoding/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<dt:data xmlns:dt="http://example.com/decoder"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://example.com/decoder  ./decoder.xsd">
    <decimal_value>1</decimal_value>
    <certification Year="1999">ISO-9001</certification>
    <certification Year="2009">ISO-27001</certification>
    <menù>baccalà mantecato</menù>
    <complex_boolean Type="2">true</complex_boolean>
    <complex_boolean Type="1">false</complex_boolean>
    <complex_boolean>true</complex_boolean>
    <complex_boolean>false</complex_boolean>
    <simple_boolean>true</simple_boolean>
    <simple_boolean>false</simple_boolean>
</dt:data>
